project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: RICH/eda.ipynb
        text: EDA
      - href: PASHA/folium-county.ipynb
        text: Explore the Data!
      - href: RICH/trendOverTime.ipynb
        text: Trends Over Time
      - href: ZENAN/commute.ipynb
        text: Commuting Numbers
      - href: ZENAN/transportation.ipynb
        text: Transportation Methods
      - href: ZENAN/bridge.ipynb
        text: Bridge Quality
      - href: conclusion.qmd
        text: Conclusion

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



