project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: RICH/eda.ipynb
        text: EDA
      - href: PASHA/explore.qmd
        text: Explore the Data
      - href: RICH/trendOverTime.ipynb
        text: Trends Over Time
      - href: RICH/compare.ipynb
        text: Quality Vs. Indicators
      - href: conclusion.qmd
        text: Conclusion

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



