project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: eda/explore.ipynb
        text: Test

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



